language: node_js

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.cache

node_js:
  - 12

stages:
  - name: test unit
    if: (type == pull_request)
  - name: deploy-test
    if: (branch == main) AND (type == pull_request)
  - name: test-e2e
    if: (branch == main) AND (type == pull_request)
  - name: deploy-prod
    if: (branch == main) AND (type != pull_request)

jobs:
  include:
    - stage: test unit
      script:
        - yarn test:coverage
    - stage: deploy-test
      script:
        - yarn deploy
    - stage: test-e2e
      script:
        - yarn cypress install
        - yarn test:e2e
    - stage: deploy-prod
      env: ENVIRONMENT=prod
      script:
        - yarn deploy
